# Generated by Django 4.1.7 on 2023-03-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(unique=True)),
                ('nombre_us', models.CharField(max_length=500)),
                ('email_us', models.EmailField(max_length=150, unique=True)),
                ('tipo_us', models.CharField(max_length=10)),
            ],
        ),
    ]
