# Generated by Django 4.1.7 on 2023-03-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lotus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
