# Generated by Django 4.1.7 on 2023-05-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lotus', '0004_modulorecurso_recurso_modulorecurso_recurso_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='historial_modulos',
            field=models.ManyToManyField(blank=True, to='Lotus.modulo'),
        ),
    ]
