# Generated by Django 4.1.7 on 2023-05-09 20:28

import Lotus.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lotus', '0006_recurso_imagen_recurso_tiempo_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='frontend/static/frontend/figuras', validators=[Lotus.validators.validate_svg]),
        ),
    ]
