# Generated by Django 4.1.7 on 2023-05-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lotus', '0008_alter_recurso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulorecurso',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
