# Generated by Django 4.1.7 on 2023-05-11 07:57

import Lotus.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lotus', '0009_modulorecurso_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='LotusMind/frontend/static/frontend/figuras', validators=[Lotus.validators.validate_svg]),
        ),
    ]
