# Generated by Django 4.1.7 on 2023-05-11 21:46

import Lotus.models
import Lotus.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lotus', '0018_alter_recurso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=Lotus.models.image_upload_path, validators=[Lotus.validators.validate_svg]),
        ),
    ]
