# Generated by Django 4.1.7 on 2023-05-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lotus', '0026_alter_respuestaencuesta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='historial_modulos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='historial_recursos',
            field=models.ManyToManyField(blank=True, to='Lotus.recurso'),
        ),
    ]
