# Generated by Django 4.1.7 on 2023-05-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
